version: "3"

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    tty: true
    restart: unless-stopped
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    
  sensor-subscribe:
    build: ./sensor-subscribe
    container_name: subscriber
    volumes:
      - ./sensor-subscribe:/sensor-subscribe

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db:rw
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  sensor-publish:
    build: ./sensor-publish
    container_name: publisher
    restart: unless-stopped
    volumes:
      - ./sensor-publish:/sensor-publish
  backend-api:
    build: ./backend-api
    container_name: fastapi
    restart: unless-stopped
    ports:
      - 8080:80

volumes:
  mongodb_data:
  config:
  data:
  log:

networks:
  default:
    name: mqtt-network